version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    environment:
      cluster.name: elasticCluster
      node.name: elasticNode1
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      ingest.geoip.downloader.enabled: "false"
      ELASTIC_PASSWORD: elastic
    ports:
      - "9200:9200"
    networks:
      - es-net
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - es-net
    depends_on:
      - elasticsearch  
    ports:
      - "5601:5601"
  
volumes:
  elastic_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpamu/dockerdata/elastic

networks:
  es-net:
    driver: bridge